- name:   Provision Image
  hosts:  default
  become: true

  tasks:
    - name: Install Apache
      package:
        name:  httpd
        state: present

    - name: Enable service httpd, and not touch the state
      service:
        name:    httpd
        enabled: yes

    - name: Start service httpd, if not started
      service:
        name:  httpd
        state: started
